name: "L'Italiano"
favicon: null
layout_spectrum: 0.74123
typography_spectrum: 0.06498389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#9C2829'
    - '#040405'
    - '#424242'
    - '#D4A0A2'
  brandStrength: 0.8125
  lightness: 0.7333182
  saturation: 0.8535079
  rhythmicContrast: 0.1688627
purpose: []
