layout_spectrum: 0.9672395
typography_spectrum: 0.06498389
color:
  saturation: 0.8535079
  lightness: 0.7333182
  brandStrength: 0.9242749
  brandColors:
    - '#FFFFFF'
    - '#9C2829'
    - '#040405'
    - '#424242'
    - '#D4A0A2'
  rhythmicContrast: 0.1688627
name: Italiano
